use_frameworks!

platform :ios, '9.0'

target 'RxRegex_Example' do
  pod 'RxRegex', :path => '../'
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'

  target 'RxRegex_Tests' do
    inherit! :search_paths

    
  end
end
