name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Deploy Cocoapods
      run : |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env :
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    - name: Deploy SPM
      run : swift package generate-xcodeproj
